# Generated by Django 3.1.2 on 2020-11-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='test',
        ),
    ]
