# Generated by Django 3.1.2 on 2020-12-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default=1, upload_to='recipe_images'),
            preserve_default=False,
        ),
    ]
