# Generated by Django 3.1.2 on 2020-11-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_framework_softuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
